# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\OneDrive\python\超级空调\UI_AC.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.resize(491, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(491, 380))
        mainWindow.setMaximumSize(QtCore.QSize(491, 380))
        mainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        mainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        mainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        mainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/img/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("")
        mainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        mainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        mainWindow.setDocumentMode(False)
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QFrame(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(20, 70, 451, 51))
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.title.setObjectName("title")
        self.label = QtWidgets.QLabel(self.title)
        self.label.setGeometry(QtCore.QRect(70, 10, 306, 33))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.AC_biankuang = QtWidgets.QFrame(self.centralwidget)
        self.AC_biankuang.setGeometry(QtCore.QRect(20, 141, 451, 101))
        self.AC_biankuang.setStyleSheet("QFrame{\n"
"border-radius: 15px;  border: 2px groove black;background:\"white\"\n"
"}\n"
"\n"
"")
        self.AC_biankuang.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AC_biankuang.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.AC_biankuang.setLineWidth(3)
        self.AC_biankuang.setMidLineWidth(0)
        self.AC_biankuang.setObjectName("AC_biankuang")
        self.degree = QtWidgets.QFrame(self.AC_biankuang)
        self.degree.setGeometry(QtCore.QRect(180, 20, 91, 51))
        self.degree.setStyleSheet("")
        self.degree.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.degree.setFrameShadow(QtWidgets.QFrame.Raised)
        self.degree.setObjectName("degree")
        self.label_shuzi = QtWidgets.QLabel(self.degree)
        self.label_shuzi.setGeometry(QtCore.QRect(20, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_shuzi.setFont(font)
        self.label_shuzi.setStyleSheet("QLabel{\n"
"border-radius: 0px;  border: 0px groove black ;color: white\n"
"}\n"
"")
        self.label_shuzi.setObjectName("label_shuzi")
        self.label_danwei = QtWidgets.QLabel(self.degree)
        self.label_danwei.setGeometry(QtCore.QRect(50, 10, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_danwei.setFont(font)
        self.label_danwei.setStyleSheet("QLabel{\n"
"border-radius: 0px;  border: 0px groove black\n"
"}\n"
"")
        self.label_danwei.setObjectName("label_danwei")
        self.frame = QtWidgets.QFrame(self.AC_biankuang)
        self.frame.setGeometry(QtCore.QRect(40, 90, 371, 31))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.AC_biankuang)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 31, 41))
        self.frame_2.setStyleSheet("QFrame{\n"
"border-radius: 10px;  border: 2px groove black\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(7, 10, 5, 2))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(7, 15, 10, 2))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setGeometry(QtCore.QRect(7, 20, 15, 2))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_3 = QtWidgets.QFrame(self.AC_biankuang)
        self.frame_3.setGeometry(QtCore.QRect(380, 50, 16, 16))
        self.frame_3.setStyleSheet("QFrame{\n"
"border-radius: 5px;  border: 2px groove black\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.AC_biankuang)
        self.frame_4.setGeometry(QtCore.QRect(410, 50, 16, 16))
        self.frame_4.setStyleSheet("QFrame{\n"
"border-radius: 5px;  border: 2px groove black\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame.raise_()
        self.degree.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 300, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 15px;  border: 2px groove black\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 300, 51, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius: 25px;  border: 2px groove black; text-align : centre\n"
"}\n"
"\n"
"")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/snow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 300, 51, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius: 25px;  border: 2px groove black; text-align : centre\n"
"}\n"
"\n"
"")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/sun.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 300, 51, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius: 25px;  border: 2px groove black; text-align : centre\n"
"}\n"
"\n"
"")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 300, 51, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-radius: 25px;  border: 2px groove black; text-align : centre\n"
"}\n"
"\n"
"")
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(10, 280, 470, 2))
        self.frame_8.setStyleSheet("border-radius: 15px;  border: 2px groove black\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 240, 400, 2))
        self.label_3.setStyleSheet("QFrame{\n"
"border-radius: 10px;  border: 2px groove black\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(10, 10, 471, 361))
        self.frame_9.setStyleSheet("border-radius: 25px;  border: 2px groove black; background: white\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"border-radius: 15px;  border: 2px groove black; text-align : centre\n"
"}\n"
"\n"
"")
        self.pushButton_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_7.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/img/mimisize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"border-radius: 15px;  border: 2px groove black; text-align : centre\n"
"}\n"
"\n"
"")
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/img/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(130, 20, 331, 41))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        self.label_2.setGeometry(QtCore.QRect(210, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_9.raise_()
        self.title.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.frame_8.raise_()
        self.AC_biankuang.raise_()
        self.label_3.raise_()
        self.frame_10.raise_()
        mainWindow.setCentralWidget(self.centralwidget)
        self.actionBY = QtWidgets.QAction(mainWindow)
        self.actionBY.setObjectName("actionBY")

        self.retranslateUi(mainWindow)
        self.pushButton_6.clicked.connect(mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "普通 の 空气调节器"))
        self.label.setText(_translate("mainWindow", "普通 の 空气调节器"))
        self.label_shuzi.setText(_translate("mainWindow", "26"))
        self.label_danwei.setText(_translate("mainWindow", "℃"))
        self.pushButton.setText(_translate("mainWindow", "开关"))
        self.label_3.setText(_translate("mainWindow", "TextLabel"))
        self.label_2.setText(_translate("mainWindow", "BY 雪中明月"))
        self.actionBY.setText(_translate("mainWindow", "BY"))
import res_rc
